packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

autoInstallPeers: false
strictPeerDependencies: true
engineStrict: true
nodeVersion: 24.18.0
pmOnFail: error
savePrefix: ""
verifyStoreIntegrity: true
updateNotifier: false
